{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kagenti-webhook.fullname" . }}-manager-rolebinding
  labels:
    {{- include "kagenti-webhook.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kagenti-webhook.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "kagenti-webhook.serviceAccountName" . }}
  namespace: {{ include "kagenti-webhook.namespace" . }}
{{- end }}
