{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "kagenti-webhook.namespace" . }}
  labels:
    {{- include "kagenti-webhook.labels" . | nindent 4 }}
{{- end }}
