apiVersion: v2
name: kagenti-webhook
description: A Kubernetes admission webhook for MCPServer resources
type: application
version: 0.1.0
appVersion: "1.16.0"
keywords:
  - webhook
  - mcp
  - toolhive
  - kagenti
